<a href="https://colab.research.google.com/github/Saifjafri212213/DS-mirai/blob/Saif-Jafri/Python_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
dct = {
    'name': ['Tom', 'Nick', 'Krish', 'Jack'],
    'age': [20, 21, 19, 18 ],
    'roll' : [1,2,3,4]
}

df = pd.DataFrame(dct)
print(df)

    name  age  roll
0    Tom   20     1
1   Nick   21     2
2  Krish   19     3
3   Jack   18     4

In [ ]:
df = pd.read_csv('student_data.csv')
df.head()

df.tail()

pd.DataFrame()

df.shape


df.describe()

df.columns

df.index

df['internet_usage']

# df.loc[df['study_hours']==11 , ['study_hours' , 'sleep_hours']].iloc[4:8]

#loc work on labels and i.loc works on indexing

# df2 = df.loc[df["study_hours"]==11]
# df.loc[4]

df.loc[df['assignments_completed']==8].iloc[1]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [ ]:
df = pd.read_csv('student_data.csv')
df.loc[df['assignments_completed']>3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df = pd.read_csv('student_data.csv')
df.head()
# df["age"] = 20 if df["assignments_completed"] > 3

#rename columns
df.rename(columns = {'assignments_completed' : 'assign_completed'} , inplace = True)

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df = pd.read_csv('student_data.csv')

dct = {
    'name': ['Tom', 'Nick', 'Krish', 'Jack'],
    'age': [20, 21, 19, 18 ],
    'roll' : [1,2,3,None]
}


df.drop('sleep_hours', axis=1)
df.drop(1, axis=0)

df.sort_values('study_hours')
df.sort_index()

df.isnull()
df.notnull()
df.fillna('saif')
df.unique()